{
    'name': 'ITC Development',
    'version': '1.0',
    'category': 'Accounting',
    'summary': 'Manage Employee Salary Advances with Accounting Integration',
    'author': 'ITC - Odoo Team',
    'depends': ['hr', 'hr_payroll', 'account', 'mail', 'base', 'web', 'helpdesk', 'stock', 'purchase'],
    'data': [
        #Security
        'security/custom_sql_report_security.xml',
        'security/salary_advance_security.xml',
        'security/disbursement_security.xml',
        #'security/security.xml',
        'security/ir.model.access.csv',

        #Data
        'data/salary_advance.xml',
        'data/bir_paperformat.xml',
        'data/a4_paperformat.xml',
        'data/cash_advance_sequence.xml',
        'data/sequence_data.xml',
        'data/expense_type_data.xml',
        'data/rfp_sequence.xml',
        'data/account_move_sequence.xml',

        #Report
        'report/sales_invoice_report.xml',
        'report/sales_order_report.xml',
        'report/purchase_order_report.xml',
        'report/official_receipt_report.xml',
        'report/service_invoice_report.xml',
        'report/credit_memo_report.xml',
        'report/debit_memo_report.xml',
        'report/report_statement_of_account_template.xml',
        'report/acknowledgement_report.xml',
        'report/bir_0619e.xml',
        'report/bir_1604e_report.xml',
        'report/cash_advance_report_template.xml',
        'report/disbursement_voucher_report.xml',
        'report/bir_1702q_report.xml',
        'report/bir_2307_report.xml',
        #Views
        #'views/salary_advance_views.xml',
        'views/purchase_journal_wizard_views.xml',
        'views/expense_sheet.xml',
        'views/expense_view.xml',
        'views/purchase_order.xml',
        'views/account_account_views.xml',
        'views/sales_order.xml',
        'views/account_move_views.xml',
        'views/sql_report_views.xml',
        'views/account_statement_menu.xml',
        'views/bir_0619e_views.xml',
        'views/bir_1702q_views.xml',
        'views/bir_2550q_views.xml',
        'views/bir_1601eq_views.xml',
        'views/bir_1604e_views.xml',
        'views/bir_1601e_views.xml',
        'views/bir_2550m_views.xml',
        'views/bir_form_view.xml',
        'views/account_payment_view.xml',
        'views/purchase_order_lines_views.xml',
        'views/account_move_lines_views.xml',
        'views/collection_receipt_views.xml',
        'views/purchase_subsidiary_journal_wizard_views.xml',
        'views/sales_journal_wizard_views.xml',
        'views/sales_subsidiary_journal_wizard_views.xml',
        # Change Request modules
        #'views/account_payment_register_views.xml',
        'views/cash_advance_views.xml',
        #'views/disbursement_voucher_views.xml',
        #'views/disbursement_voucher_line_views.xml',
        #'views/disbursement_payment_views.xml',
        #'views/disbursement_menu.xml',
        #'views/request_for_payment_views.xml',
       

    ],

    'assets': {
        'web.assets_backend': [
            'itc_internal_dev/static/src/css/custom_buttons.css',
            'itc_internal_dev/static/src/css/bir_button.css',
            'itc_internal_dev/static/src/css/required.css',
            'itc_internal_dev/static/src/js/sql_report_filter.js',
        ],
    },
    'installable': True,
    'application': True,
    'icon': '/itc_internal_dev/static/description/ITCLOGO.jpg',
}
